Feature/config-showSubject
pixx-io/jsdk pull request #12
Opened 2022-03-09 14:58 UTC by IlChillberto

Added new configuration "showSubject".
Implemented helper-file for global functions

2022-03-14 11:59 UTC, dannystey requested changes
In general I would rather prefer a websocket class with listener registrations instead of a single converter solution

2022-03-14 11:59 UTC, dannystey commented on src/App.svelte
> +      const websocketUrl = 'wss://' + $domain.replace(/^(http|https):\/\//, '') + '/gobackend/ws?accessToken=' + $accessToken;
so if this is in a watch you have to check if a websocket connection already exists. and if so you have to close before you connect again.

2022-03-14 11:59 UTC, dannystey commented on src/helper.js
> +}
why this helper class for just checking if type is boolean? typeof value === 'boolean' does the same isn't it?

2022-03-14 13:55 UTC, IlChillberto commented on src/helper.js
> +}
I have read that typeof and string comparisons are slower than direct boolean-comparisons.
That is why i used this approach instead of your solution.
I outsourced this function for better readability only.

2022-03-16 08:31 UTC, dannystey requested changes

2022-03-16 08:31 UTC, dannystey commented on src/helper.js
> +}
than I would prefer a static function, so that you don't have to re initiate the class every time and can call isBoolean by HELPER.isBoolean. What do you think?

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +      console.info('WS: Recieved Message:', event.data);
would remove this console.info

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +      console.info('WS: no connection possible. access token is missing.');
would remove this console.info

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +        new API().callAccessToken().then({
would wrap new API() in (new API()). I don't think that this operation works without wrapping in parentheses

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +      console.info('WS: Try to reconnect', 'connection tries left:', this.reconnectionAttempts);
would remove this console.info

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +      console.info('FRONTEND CLOSES CONNECTION');
would remove this console.info

2022-03-16 08:31 UTC, dannystey commented on src/websocket.js
> +}
new line at the end

2022-03-16 11:00 UTC, dannystey requested changes

2022-03-16 11:00 UTC, dannystey commented on src/main.js
> +    console.log('=> getMedia: ', config);
remove console.log

2022-03-16 11:01 UTC, merged